branches:
  only:
    - master

language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
install: "pip install -r requirements.txt"

script:
  - python setup.py install
  - travis_wait 20 py.test -v -s -m zran_test         --nelems 16777216
  - travis_wait 20 py.test -v -s -m zran_test         --nelems 16777216  --concat
  - travis_wait 20 py.test -v -s -m indexed_gzip_test --nelems 16777216
  - travis_wait 20 py.test -v -s -m indexed_gzip_test --nelems 16777216  --concat
  - travis_wait 30 py.test -v -s -m zran_test         --nelems 268435456
  - travis_wait 30 py.test -v -s -m zran_test         --nelems 268435456 --concat
  - travis_wait 30 py.test -v -s -m indexed_gzip_test --nelems 268435456
  - travis_wait 30 py.test -v -s -m indexed_gzip_test --nelems 268435456 --concat

# TODO These are needed for testing reads greater than 4GB (i.e.
#      reading >= 2**32 bytes in one go). They need time and
#      > 4GB of RAM. I don't think travis-ci can handle them.
#  - travis_wait 40 py.test -v -s -m zran_test         --nelems 536871012
#  - travis_wait 40 py.test -v -s -m zran_test         --nelems 536871012  --concat
#  - travis_wait 40 py.test -v -s -m indexed_gzip_test --nelems 536871012
#  - travis_wait 40 py.test -v -s -m indexed_gzip_test --nelems 536871012  --concat 
