branches:
  only:
    - master

language: python
python:
  - "2.7"
  - "3.5"

env:

  - TEST_SUITE=zran_test         NITERS=5000 NELEMS=1000000  TEST_PATTERN="not test_readbuf_spacing_sizes and not test_seek_then_read_block"
  - TEST_SUITE=zran_test         NITERS=1000 NELEMS=1000000  TEST_PATTERN="test_readbuf_spacing_sizes"
  - TEST_SUITE=zran_test         NITERS=1000 NELEMS=1000000  TEST_PATTERN="test_seek_then_read_block"
  - TEST_SUITE=indexed_gzip_test NITERS=5000 NELEMS=1000000

  - TEST_SUITE=zran_test         NITERS=5000 NELEMS=1048576  TEST_PATTERN="not test_readbuf_spacing_sizes and not test_seek_then_read_block"
  - TEST_SUITE=zran_test         NITERS=1000 NELEMS=1048576  TEST_PATTERN="test_readbuf_spacing_sizes"
  - TEST_SUITE=zran_test         NITERS=1000 NELEMS=1048576  TEST_PATTERN="test_seek_then_read_block"
  - TEST_SUITE=indexed_gzip_test NITERS=5000 NELEMS=1048576

# NELEMS=something arbitrary that is not divisible 
# by any of the default buffer/spacing sizes 
  - TEST_SUITE=zran_test         NITERS=5000 NELEMS=2000000  TEST_PATTERN="not test_readbuf_spacing_sizes and not test_seek_then_read_block"
  - TEST_SUITE=zran_test         NITERS=500  NELEMS=2000000  TEST_PATTERN="test_readbuf_spacing_sizes"
  - TEST_SUITE=zran_test         NITERS=500  NELEMS=2000000  TEST_PATTERN="test_seek_then_read_block"
  - TEST_SUITE=indexed_gzip_test NITERS=5000 NELEMS=2000000
  
# NELEMS=16777216 works out to be 128MB uncompressed
  - TEST_SUITE=zran_test         NITERS=5000 NELEMS=16777216 TEST_PATTERN="not test_readbuf_spacing_sizes and not test_seek_then_read_block"
  - TEST_SUITE=zran_test         NITERS=500  NELEMS=16777216 TEST_PATTERN="test_readbuf_spacing_sizes"
  - TEST_SUITE=zran_test         NITERS=500  NELEMS=16777216 TEST_PATTERN="test_seek_then_read_block"
  - TEST_SUITE=indexed_gzip_test NITERS=5000 NELEMS=16777216


# TODO This is needed for testing reads greater than 4GB (i.e.
#      reading >= 2**32 bytes in one go). They need time and
#      > 4GB of RAM. I don't think travis-ci can handle them. 
#  - NELEMS=536871012

# TODO I also want to test bigger files (~2GB), but these tests
#      are currently take a bit too long for travis-ci.
#  - NELEMS=268435456
  
install: "pip install -r requirements.txt"

script:
  - python setup.py install
  - python setup.py test --addopts "-v -s -m \"$TEST_SUITE\" -k \"$TEST_PATTERN\" --nelems \"$NELEMS\" --niters \"$NITERS\""
  - python setup.py test --addopts "-v -s -m \"$TEST_SUITE\" -k \"$TEST_PATTERN\" --nelems \"$NELEMS\" --niters \"$NITERS\" --concat"
